---
title: "Final Project"
output: html_notebook
name: "Adam Whiteside"
---
Research Question:
What is the relationship between a player on the Dallas Mavericks' salary and production on the court in the 2021-2022 season?

Data Intake:
```{r}
library(tidyverse)
library(rvest)

BasketballReference<- "https://en.wikipedia.org/wiki/2021%E2%80%9322_Dallas_Mavericks_season"
StatsTable <- BasketballReference %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
  PlayerGameStats <- StatsTable[[22]]
  head(PlayerGameStats)
```

```{r}
library(tidyverse)
library(rvest)

BasketballReference<- "https://www.basketball-reference.com/teams/DAL/2022.html"
AdvancedStatsTable <- BasketballReference %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
  AdvancedPlayerGameStats <- AdvancedStatsTable[[6]]
  (AdvancedPlayerGameStats)
```


```{r}
SalaryWebsite <- "https://hoopshype.com/salaries/dallas_mavericks/2021-2022/"
SalaryData<- Salaries %>%
  read_html() %>%
  html_nodes(css = "table") %>%
  html_table(fill = TRUE)
  SalaryTable <- SalaryData[[1]]
  head(SalaryTable)
  
```




```{r}

colnames(AdvancedPlayerGameStats)[2] <- "PlayerName"
colnames(AdvancedPlayerGameStats)[18] <- "a"
colnames(AdvancedPlayerGameStats)[23] <- "b"

colnames(SalaryTable)[1] <- "PlayerName"
colnames(SalaryTable)[3] <- "Player Salaries(adjusted for inflation)"

colnames(PlayerGameStats)[1] <- "PlayerName"
```

```{r}
SalaryTableFixed<-
  SalaryTable%>%
  filter(PlayerName != "Player")
```


```{r}

AdvancedPlayerGameStats$PlayerName <-
  str_replace_all(AdvancedPlayerGameStats$PlayerName, c("č" = "c", "ć" = "c", "ņ" = "n", "ģ" = "g", "ā" = "a"))


AdvancedPlayerGameStats$PlayerName<-
  str_replace(AdvancedPlayerGameStats$PlayerName, " Jr", "")

AdvancedPlayerGameStats$PlayerName<-
  str_remove(AdvancedPlayerGameStats$PlayerName, "\\.$")
  
SalaryTableFixed$PlayerName<-
  str_replace(SalaryTableFixed$PlayerName, " Jr", "")



```



```{r}
SalaryandAdvanced<-
  right_join(SalaryTableFixed,AdvancedPlayerGameStats, by="PlayerName")
  colnames(SalaryandAdvanced)[2] <- "PlayerSalaries"

SalaryandAdvanced
```



```{r}
SalaryandAdvanced$PlayerSalaries<-
  parse_number(SalaryandAdvanced$PlayerSalaries)

SalaryandAdvanced$`Player Salaries(adjusted for inflation)`<-
  parse_number(SalaryandAdvanced$`Player Salaries(adjusted for inflation)`)

```

```{r}
SalaryandAdvanced[27,"PlayerSalaries"] <- 38800000; SalaryandAdvanced
SalaryandAdvanced[27,"Player Salaries(adjusted for inflation)"] <- 42672124; SalaryandAdvanced
```

```{r}
SalaryandAdvanced<-
  SalaryandAdvanced%>%
  mutate(newPER=(PER+15))%>%
  mutate(PertimesMP=(newPER*MP))%>%
  mutate( Salary_PER_Ratio = (PlayerSalaries/PertimesMP))%>%
  arrange(Salary_PER_Ratio)

```

```{r}
SalaryandAdvanced[which.max(SalaryandAdvanced$Salary_PER_Ratio),]%>%
  select(PlayerName, Salary_PER_Ratio)%>%
  summarise(PlayerNameofHighestRatio=PlayerName, Ratio=Salary_PER_Ratio)
```

```{r}
SalaryandAdvanced[which.min(SalaryandAdvanced$Salary_PER_Ratio),]%>%
  select(PlayerName, Salary_PER_Ratio)%>%
  summarise(PlayerNameofLowestRatio=PlayerName, Ratio=Salary_PER_Ratio)
```
```{r}


PlayerRatioPlot<-
  SalaryandAdvanced%>%
  head(5)%>%
  ggplot(aes(x=reorder(PlayerName, Salary_PER_Ratio), y=Salary_PER_Ratio))+
  geom_bar(stat="identity", color="blue", fill="lightblue")+
  ggtitle("Top 5 Best Salary to Production Ratios from Dallas Mavericks 2021-2022 Season")+
  xlab("Player Name")+
  ylab("Salary to Production Ratio")
PlayerRatioPlot


```
```{r}
PlotbyMinutes<- function(minimum_minutes, minimum_age){
  PlayerRatioPlot<-
  SalaryandAdvanced%>%
  filter(MP>minimum_minutes)%>%
  filter(Age>minimum_age)%>%
  head(5)%>%
  ggplot(aes(x=reorder(PlayerName, Salary_PER_Ratio), y=Salary_PER_Ratio))+
  geom_bar(stat="identity", color="blue", fill="lightblue")+
  ggtitle(paste("Top 5 Best Salary to Production Ratios with more than", minimum_minutes,
                "minutes \n and older than" ,minimum_age, "from Dallas Mavericks in 2021-2022 Season"))+
  xlab("Player Name")+
  ylab("Salary to Production Ratio")
  return(PlayerRatioPlot)
}
  PlotbyMinutes(1000, 28)
```
```{r}
MeanAgeStats<-
  SalaryandAdvanced%>%
  group_by(Age)%>%
  summarise(MeanPerAge= mean(Salary_PER_Ratio))

MeanAgeStats
```

```{r}

PlayerRatioPlot<-
  MeanAgeStats%>%
  ggplot(aes(x=Age, y=MeanPerAge))+
  geom_smooth(stat="identity", linewidth=2, linetype="solid")+
  ggtitle("Salary to Production Ratio based on Age from Dallas Mavericks players \n in the 2021-2022 Season")+
  xlab("Age")+
  ylab("Salary to Production Ratio")
PlayerRatioPlot
```